services:
  - type: web
    name: liher-fashion
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn prjLiherfashion.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DB_NAME
        value: liherfashion
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: ""
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 3306
